---
- hosts: localhost
  vars:
    lxd_containers:
      - name: container
        alias: "{{ lxd_alias }}"
        profiles:
          - default
  pre_tasks:
    - name: Multiple containers vars setup
      block:
        - name: Setup empty var
          set_fact:
            lxd_containers: []
        - name: Create the list of containers to deploy
          set_fact:
            lxd_containers: |
                {{
                    lxd_containers + [{
                        'name': item,
                        'alias': lxd_alias,
                        'profiles': ['default']
                    }]
                }}
          with_items: "{{ lxd_containers_names }}"
      when:
        - lxd_containers_names is defined
        - lxd_containers_names != ''
  roles:
    - lxd

# Make a bootstrap role for installing common packages
- hosts: all:!localhost
  tasks:
    - name: Installing common software on containers
      package:
        name: "{{ item }}"
      with_items:
        - git
        - sudo
        - tar
        - cron
        - crontabs
        - unzip
      ignore_errors: true
...
