---
- hosts: localhost
#  become: yes
  vars:
    lxd_use_lts: true
    lxd_profiles:
      - name: "default"
        description: "Default LXD profile"
        config:
          security.privileged: "true"
          environment.http_proxy: ""
          user.network_mode: ""
        devices:
          eth0:
            nictype: "bridged"
            parent: "lxdbr0"
            type: "nic"
          root:
            path: "/"
            type: "disk"

    lxd_bridge:
      ipv4:
        address: "192.168.2.1/24"
        nat: "true"

    lxd_containers:
      - name: container
        alias: "{{ lxd_alias }}"
        profiles:
          - default
  pre_tasks:
    - name: Multiple containers vars setup
      block:
        - name: Setup empty var
          set_fact:
            lxd_containers: []
        - name: Create the list of containers to deploy
          set_fact:
            lxd_containers: |
                {{
                    lxd_containers + [{
                        'name': item,
                        'alias': lxd_alias,
                        'profiles': ['default']
                    }]
                }}
          with_items: "{{ lxd_containers_names }}"
      when:
        - lxd_containers_names is defined
        - lxd_containers_names != ''
  roles:
    - lxd
