---
- hosts: localhost
  vars:
    git_repos:
      - src: https://github.com/Nani-o/ansible-role-lxd
        name: lxd
        path: "{{ playbook_dir }}/roles/"
    file_downloads:
      - src: https://raw.githubusercontent.com/Nani-o/ansible-inventory-lxc/master/lxd.py
        name: lxd.py
        mode: "0775"
        path: "{{ playbook_dir }}/inventory/"
  tasks:
    - name: Make sure folders exists
      file:
        path: "{{ item.path }}"
        state: directory
      when: item.path is defined
      with_items:
        - "{{ git_repos | default([]) }}"
        - "{{ file_downloads | default([]) }}"

    - name: Clone/Pull of repositories
      git:
        repo: "{{ item.src }}"
        dest: "{{ item.path }}/{{ item.name }}"
        clone: yes
        update: yes
        force: yes
      when: git_repos is defined
      with_items: "{{ git_repos }}"

    - name: Download files
      get_url:
        url: "{{ item.src }}"
        dest: "{{ item.path }}/{{ item.name }}"
      when: files_downloads is defined
      with_items: "{{ file_downloads }}"
