---
- hosts: localhost
  vars:
    lxd_deploy_profiles:
      - name: "default"
        description: "Default LXD profile"
        config:
          security.privileged: "true"
          environment.http_proxy: ""
          user.network_mode: ""
        devices:
          eth0:
            nictype: "bridged"
            parent: "lxdbr0"
            type: "nic"
          root:
            path: "/"
            pool: "default"
            type: "disk"

    lxd_deploy_networks:
      - name: lxdbr0
        config:
          ipv4.address: "192.168.2.1/24"
          ipv4.nat: "true"
          ipv6.address: "none"
        description: "Default Network"

    lxd_deploy_containers:
      - name: container
        alias: "{{ lookup('env','lxd_container_alias') }}"
        profiles:
          - default
  roles:
    - lxd-deploy
